# Generated by Django 5.0.4 on 2024-04-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='doc_cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
